site:
  name: Christian Enevoldsen
  site: 'https://chrs.gg'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Christian Enevoldsen
    template: '%s · chrs.gg'
  description: 'Portfolio of Christian Enevoldsen · Software Developer focused on modern web technologies and building useful, thoughtful digital products.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Christian Enevoldsen
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@chrsapp' # update to your handle if you have one
    site: '@chrsapp'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Supports custom slugs for blog posts
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # You can rename this to "notes" or "journal" if that fits better
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # Add your GA ID here if you use Google Analytics

ui:
  theme: 'system' # Users get light/dark based on their preference
